# Copyright 2020 The Kubernetes Authors.
# SPDX-License-Identifier: Apache-2.0

apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: "kuma"
  labels:
    app.kubernetes.io/name: "kuma"
spec:
  selector:
    matchLabels:
     app.kubernetes.io/name: "kuma"
  componentKinds:
    - group: v1
      kind: Service
    - group: apps
      kind: StatefulSet
  addOwnerRef: true
  descriptor:
    type: "kuma"
    keywords:
      - "cms"
      - "blog"
      - "wordpress"
    links:
      - description: About
        url: "https://kuma.io/"
    version: "0.7"
    description: "Kuma is the open-source control plane for service mesh, delivering high performance and reliability with Envoy"
    icons:
      - src: "https://github.com/Kong/gcp-marketplace/blob/main/GKE/Kuma/screenshots/kuma.jpeg"
        type: "image/png"
